ShutDownReason=Reason for shutdown
RestartMessage=Message to display
RestartMessageDescription=This will be displayed on most Jenkins pages while Jenkins is preparing to restart. A default message will be added if you leave it empty.
UpdateMessage=Update message
